#similarities

```{r message=FALSE, warning=FALSE}
corpus_final <- read_csv("data supervised_L/corpus_final_before_after.csv")

tweet.cp <- corpus(corpus_final$text, corpus_final$Document)
tweet.tfidf <- dfm_tfidf(dfm(tweet.cp, remove_punct = TRUE, remove_numbers=TRUE,
                             remove = stopwords("english")))

#jaccard index
tweet.jac <- textstat_simil(tweet.tfidf, method = "jaccard", margin = "documents")

library(reshape2)
tweet.jac.mat <- melt(as.matrix(tweet.jac)) # Convert the object to matrix then to data frame 
ggplot(data = tweet.jac.mat, aes(x=Var1, y=Var2, fill=value))+
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                       midpoint = 0.5, limit = c(0,1), name="Jaccard")+
  geom_tile() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
#clustering
```{r}
tweet.hc <- hclust(dist(tweet.jac))
## crude.hc <- hclust(dist(1 - crude.jac)) # use this line for Jaccard
## crude.hc <- hclust(dist(1 - crude.cos)) # use this line for Cosine
plot(tweet.hc)


```

