---
title: "brouillon"
author: "Cédric Vuignier"
date: "11/6/2020"
output: html_document
---


```{r echo=FALSE, message=FALSE, warning=FALSE}
# trump analysis
library(readr)
library(lubridate)
library(ggplot2)
library(kableExtra)
library(tidyverse)
library(tidytext)
library(textdata)
library(wordcloud)

TRUMP_all_tweet <- read_csv("data_before/TRUMP_all_tweet.csv")

#remove amp word" because I don't know why the sign & is transformed into "amp"
TRUMP_all_tweet <- gsub("amp","", TRUMP_all_tweet)
TRUMP_all_tweet <- as_tibble(TRUMP_all_tweet)

#transform in a tibble
crude.trump <- as_tibble(data.frame(TRUMP_all_tweet))

#tokenization
crude.tok <- unnest_tokens(crude.trump, output="word", input="value", to_lower=TRUE, strip_punct=TRUE, 
                           strip_numeric=TRUE)
#remove stop words
crude.tok <- anti_join(crude.tok, stop_words, by = "word")


#count the words use by trump 
crude.fr <- crude.tok %>%  count(word, sort=TRUE) %>% ungroup()

#wordcloud
crude.fr <- crude.fr 
wordcloud(words=crude.fr$word, freq=crude.fr$n, max.words=120, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))
##########################################################################################
#sentimental analysis

crude.sent <- crude.tok %>%
  inner_join(get_sentiments("nrc"))


crude.sent %>% group_by(sentiment) %>% 
  summarize(n = n()) %>% 
  ggplot(aes(x = sentiment, y = n, fill = sentiment)) + 
  geom_bar(stat = "identity", alpha = 0.8)
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
#biden
BIDEN_all_tweet <- read_csv("data_before/BIDEN_all_tweet.csv")

#remove amp word" because I don't know why the sign & is transformed into "amp"
BIDEN_all_tweet <- gsub("amp","", BIDEN_all_tweet)
BIDEN_all_tweet <- as_tibble(BIDEN_all_tweet)

#transform in a tibble
crude.biden <- as_tibble(data.frame(BIDEN_all_tweet))

#tokenization
crude.tok <- unnest_tokens(crude.biden, output="word", input="value", to_lower=TRUE, strip_punct=TRUE, 
                           strip_numeric=TRUE)
#remove stop words
crude.tok <- anti_join(crude.tok, stop_words, by = "word")


#count the words use by trump 
crude.fr <- crude.tok %>%  count(word, sort=TRUE) %>% ungroup()

#wordcloud
crude.fr <- crude.fr 
wordcloud(words=crude.fr$word, freq=crude.fr$n, max.words=120, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))


```

